In [1]:
%load_ext autoreload
%autoreload 2

In [70]:
import numpy as np
from sklearn.decomposition import nmf
from sklearn.preprocessing import normalize
from numpy import linalg
from util import *
import NMF
from NMF import projection

In [161]:
U0,V0 = NMF.init(100,5)
P = U0 @ V0.T
U1, V1 = NMF.init(100,30)
U,V,F = NMF.subroutine(P,U1,V1) 

Starting error 0.2987996225826591
Min norm of U: 0.3497540199739333
Complete iter 0: 0.17376137473283906
Min norm of U: 0.3497540200031793
Complete iter 1: 0.16688066277282493
Min norm of U: 0.34975402000501976
Complete iter 2: 0.16583327989686594
Min norm of U: 0.3497540200035101
Complete iter 3: 0.16518583878015491
Min norm of U: 0.3497540200012515
Complete iter 4: 0.16459005802282756
Min norm of U: 0.3497540199989466
Complete iter 5: 0.16401133140282226
Min norm of U: 0.3497540199967168
Complete iter 6: 0.16344514399711602
Min norm of U: 0.3497540199945862
Complete iter 7: 0.16289098855214204
Min norm of U: 0.34975401999255684
Complete iter 8: 0.1623484266843602
Min norm of U: 0.3497540199906256
Complete iter 9: 0.16181719147945903
Min norm of U: 0.34975401998879146
Complete iter 10: 0.16129704049271965
Min norm of U: 0.34975401998705236
Complete iter 11: 0.16078767779781886
Min norm of U: 0.3497540199854063
Complete iter 12: 0.16028885187406386
Min norm of U: 0.34975401998385164
Co

C:\Research\NMF2\State-Aggregation\NMF.py:22: RuntimeWarning: divide by zero encountered in double_scalars
  while iter_<max_iter and (iter_<30 or (F[iter_-3:iter_-1].mean()-F[iter_])/F[iter_]> tol) :


Min norm of U: 0.3497540199691966
Complete iter 33: 0.15191449072347932
Min norm of U: 0.34975401996916977
Complete iter 34: 0.15159865587134344
Min norm of U: 0.3497540199692004
Complete iter 35: 0.15128888805213553
Min norm of U: 0.34975401996928773
Complete iter 36: 0.15098508071387068
Min norm of U: 0.34975401996943023
Complete iter 37: 0.15068704488625265
Min norm of U: 0.34975401996962646
Complete iter 38: 0.15039495560197083
Min norm of U: 0.34975401996987576
Complete iter 39: 0.150108446354558
Min norm of U: 0.3497540199701787
Complete iter 40: 0.14982764975846904
Min norm of U: 0.34975401997053296
Complete iter 41: 0.14955212813516244
Min norm of U: 0.34975401997093625
Complete iter 42: 0.1492817782979076
Min norm of U: 0.3497540199713884
Complete iter 43: 0.14901654654395782
Min norm of U: 0.34975401997188954
Complete iter 44: 0.14875661676851978
Min norm of U: 0.3497540199724398
Complete iter 45: 0.14850170468832857
Min norm of U: 0.34975401997303635
Complete iter 46: 0.1482

Complete iter 146: 0.13669955995160324
Min norm of U: 0.3497540201625317
Complete iter 147: 0.1366546173155988
Min norm of U: 0.349754020164979
Complete iter 148: 0.13661047752492866
Min norm of U: 0.34975402016743024
Complete iter 149: 0.1365670700146116
Min norm of U: 0.3497540201698875
Complete iter 150: 0.1365242363003285
Min norm of U: 0.3497540201723498
Complete iter 151: 0.13648197576291884
Min norm of U: 0.3497540201748155
Complete iter 152: 0.1364402899310461
Min norm of U: 0.34975402017728274
Complete iter 153: 0.13639916388335643
Min norm of U: 0.3497540201797528
Complete iter 154: 0.13635856881739497
Min norm of U: 0.3497540201822264
Complete iter 155: 0.13631849433271756
Min norm of U: 0.3497540201847032
Complete iter 156: 0.1362790621724421
Min norm of U: 0.34975402018718255
Complete iter 157: 0.13624018005927535
Min norm of U: 0.3497540201896632
Complete iter 158: 0.1362018536100746
Min norm of U: 0.34975402019214563
Complete iter 159: 0.13616418328370217
Min norm of U: 

In [162]:
V.T@np.ones(100)

array([1.00074841, 1.00014031, 1.00035939, 1.00110369, 1.00004676,
       1.00000435, 1.00018849, 1.00053714, 1.00011856, 1.00022782,
       1.00183603, 1.000303  , 1.00007348, 1.00013097, 1.00000414,
       1.00072638, 1.00007922, 1.00021734, 1.00050173, 1.00024691,
       1.00026874, 1.00016237, 1.00190965, 1.00021585, 1.00125685,
       1.00266618, 1.00034062, 1.00004367, 1.00116287, 1.00117082])

In [152]:
F[-10:-2].mean()/F[-1]-1

0.0009213187536791789

In [102]:
X = np.array([[1,2,3],[2,3,4],[4,5,1], [5,6,7]])

In [139]:
X, _ = NMF.init(1000,300)

In [140]:
projection(X)@np.ones(300)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [103]:
X = normalize(X, axis = 1, norm = 'l1')

In [122]:
X

array([[0.06941321, 0.06410487, 0.05965322, ..., 0.04335577, 0.03270544,
        0.0077916 ],
       [0.02117122, 0.01093749, 0.0515395 , ..., 0.02881986, 0.01042845,
        0.05205485],
       [0.00413641, 0.05993478, 0.01478352, ..., 0.05946633, 0.03079596,
        0.01920657],
       ...,
       [0.03928257, 0.02055594, 0.0523629 , ..., 0.05424119, 0.00498542,
        0.05986655],
       [0.02460946, 0.03248597, 0.0314086 , ..., 0.02310619, 0.06975204,
        0.02649812],
       [0.05245583, 0.03165086, 0.00822645, ..., 0.03122536, 0.0518128 ,
        0.0441404 ]])

In [128]:
d,s = X.shape
proj = np.zeros([d,s])
for i in range(d):
    temp = sorted(X[i,:], reverse = True)
    print(temp)
    print([sum([temp[k] - temp[j] for k in range(j)]) for j in range(s)])
    l = np.argmax([sum([temp[k] - temp[j] for k in range(j)]) for j in range(s)])
    print(l)
    eta = 1/l * (1 - sum(temp[:l+1]))
    print(eta)
    proj[i,:] = X[i,:] + eta * np.ones(s)
    proj[i,:] = proj[i,:] * (proj[i,:]>0)

[0.06941320977372469, 0.06821778512919224, 0.0680189763133825, 0.06410486851672688, 0.05965322436564736, 0.05782250706662808, 0.055946201645924044, 0.0544010757080291, 0.04748894869008351, 0.043878907875754644, 0.043355769692211193, 0.04240628445884236, 0.04156455446703416, 0.04025659484785814, 0.040012926766964566, 0.03291364707566122, 0.03270544449395281, 0.0303159476667703, 0.028352742998193278, 0.023737534554900037, 0.014074021158240307, 0.01013503812662497, 0.007791598778269903, 0.006494857258297691, 0.005920382566933588, 0.0035449367065767553, 0.0033981596151047458, 0.002526754924540509, 0.0010257009493808288, 0.0005213978085496816]
[0, 0.0011954246445324418, 0.0015930422761519375, 0.013335365666118787, 0.031141942270436873, 0.04029552876553326, 0.051553361289757474, 0.06236924285502208, 0.11766625899858683, 0.15015662632754662, 0.1553880081629811, 0.16583234573003827, 0.17593310563173672, 0.19293658068102498, 0.19634793381353496, 0.30283712918308514, 0.30616837049041973, 0.34678

In [129]:
proj@np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
linalg.norm(U1, axis = 0)

array([0.53241936, 0.51516142, 0.56591678, 0.5478737 , 0.55202242,
       0.5797277 , 0.54487367, 0.52409502, 0.56313834, 0.54604022,
       0.56455982, 0.57231401, 0.52451728, 0.52685388, 0.53150765,
       0.52273208, 0.52782032, 0.57164826, 0.52930216, 0.52793249,
       0.55057925, 0.54528688, 0.54109525, 0.53872655, 0.53722027,
       0.52558322, 0.56996626, 0.57547276, 0.54899152, 0.54479003])

In [34]:
len(np.array([1,2,3]).shape)

1

In [ ]:
V[41]

In [ ]:
A = pd.read_csv(r'100_matrix_2.csv').values

In [ ]:
1e-6

In [ ]:
U,V=init(2000,5)

In [ ]:
def non_negative_factorization(X, s0, tol=1e-4, max_iter=200):
    d = X.shape[0]
    U,V = init(d,s0)
    iter_ = 0
    F = np.zer
    while True:
        while (iter_>30 or (F[-31:-2].mean()-F[-1])/F[-1]> 0.001) and iter_<max_iter:
            iter_ += 1
    return W,H,n_iter

def subroutine(X,U,V,s, tol):
    iter_ = 0
    while (iter_>30 or (F[-31:-2].mean()-F[-1])/F[-1]> 0.001) and iter_<max_iter:
        iter_ += 1
        U,V,s = reduce(U,V)
        U,V = palm(X,U,V, lambda_ = ,eps = )
    return U,V
        
def reduce(U,V, drop_threshold = 0.001):
    norm = linalg.norm(U, ord = 2, axis = 0)
    drop = np.where(norm<drop_threshold)
    U = np.delete(U, drop, axis = 1)
    V = np.delete(V, drop, axis = 1)
    return U,V,U.shape[1] - len(drop)

def compress1(U, V):
    import sympy
    d,s = U.shape
    combination = [[U[j,i] * V[k,i] for i in range(s)] for j in range(d) for k in range(d)]
    _, columns = sympy.Matrix(t).rref(combination)
    U = normalize(U[:,columns], axis = 1, norm = 'l1')
    V = V[:,columns]
    return U,V
    
def compress2(U, V, ind_threshold):
    pass
      
def expand(U,V,u,v):
    U = np.diag(np.ones(U.shape[0]) - kappa * u)@U
    U = np.concatenate((U, kappa * u), axis = 1)
    V = np.concatenate((V, 1/(v.T@np.ones(V.shape[0]))@v), axis = 1)
    return U,V

def positive_normalize(x):
    x = x * (x>0)
    return normalize(x)
    
def check_global_optimality(P,X,mu, threshold, iter_, lr,extra_eps, lambda_):
    t = mu@np.ones(X.shape[0]) - 2(X - P)
    u,v = init(X.shape[0],1)
    change = 1
    iter_ = 0
    new_sigma = u.T@t@v
    while change>threshold and iter_<100:
        old_sigma = new_sigma
        u = positive_normalize(u + lr * t@v)
        v = positive_normalize(v + lr * t.T@u)
        new_sigma = u.T@t@v
        change = new_sigma / old_sigma - 1
    return new_sigma < (1+extra_eps) * lambda_, u, v

def norm(X):
    return linalg.norm(X, ord = 2, axis = 0)

def palm(X, U, V, lambda_, eps,):
    c = 1/(gamma1 * (linalg.norm(V.T@V)+ lambda_/eps))
    d = 1/(gamma2 * (linalg.norm(U.T@U) + lambda_ * np.sqrt(d) * linalg.norm(U)))
    F_U = -(X - U@V.T)@V + lambda_ * U * np.diag([linalg.norm(V[:,j])/linalg.norm(U[:,j]) for j in range(U.shape[1])])
    U = projection(U - c * F_U)
    F_V = -(X - U@V.T)@U + lambda_ * V * np.diag([linalg.norm(U[:,j])/linalg.norm(V[:,j]) for j in range(U.shape[1])])
    V = projection(V - d * F_V)
    return U,V

def projection(X):
    d,s = X.shape
    proj = np.zeros(d,s)
    for i in range(d):
        l = np.argmax([sum([X[i,k] - X[i,j] for k in range(j)]) for j in range(s)])
        eta = 1/l * (1 - sum(X[i,:l]))
        proj[i,:] = X + eta * np.ones(s)
        proj[i,:] = proj[i,:] * (proj[i,:]>0)
    return proj

def init(d, s0):
    U = normalize(np.random.rand(d,s0), axis = 1, norm = 'l1')
    V = normalize(np.random.rand(d,s0), axis = 0, norm = 'l1')
    return U,V

In [ ]:
t.shape

In [ ]:
np.array([1,2,3]).T.shape

In [ ]:
np.concatenate((t, np.array([[1,2,3]]).T), axis = 1)

In [ ]:
t = np.array([[1,1,2],[3,3,1], [4,4,3]])
u,v,d = np.linalg.svd(t)

In [ ]:
u,v,d 

In [ ]:
u[:,:2] @ np.diag(v[:2]) @ d[:2,:3]

In [ ]:
t = np.array([[1,1,3,5,6],[3,3,3,5,6], [4,4,3,5,6]])

In [ ]:
lambdas, V =  np.linalg.eig(t.T)
t[lambdas == 0,:]

In [ ]:
import sympy

In [ ]:
sympy.Matrix(t).rref()

In [ ]:
lambdas

In [ ]:
scipy.linalg.lstsq()

In [ ]:
np.linalg.lstsq(np.array([[1,2],[2,4],[3,6]]), np.zeros(3))

In [ ]:
[[U[j,i] * V[k,i] for i in range(3)] for j in range(4) for k in range(4)]

In [ ]:
X,res,rank,s = np.linalg.lstsq([[U[j,i] * V[k,i] for i in range(3)] for j in range(4) for k in range(4)],np.zeros(16)) 

In [ ]:
X

In [ ]:
U, V = init(3,3)

In [ ]:
U.shape[1]

In [ ]:
reduce(U,V, 0.5)

In [ ]:
t = np.random.rand(3,3)

In [ ]:
normalize(t, axis = 1, norm = 'l1')

In [ ]:
t.sum(axis = 1).reshape(1,3)

In [ ]:
t.sum(axis = 1)

In [ ]:
0.07150122 / 1.94110118

In [ ]:
(t/t.sum(axis = 1).reshape(3,1)).sum(axis = 1)

In [ ]:
t.sum(axis = 1)

In [ ]:
t/t.sum(axis = 1)

### Classic NMF

In [ ]:
W,H,niter = nmf.non_negative_factorization(A, n_components = 50, verbose = True,)

In [ ]:
W,H,niter = nmf.non_negative_factorization(A, n_components = 1, verbose = True,)

In [ ]:
def inspect(A):
    plt.hist(A.sum(axis = 0), bins = 15,range = (0,15))
    plt.show()
    plt.hist(A.sum(axis = 1), bins = 15,range = (0,15))
    plt.show()

In [ ]:
A, count = get_matrix('100.csv')

In [ ]:
man = get_zones()
joint = get_joint_grid(man, 100, 0)

In [ ]:
sorted_count = pd.DataFrame(count).sort_values('count',ascending = False)

In [ ]:
sorted_count.head()

In [ ]:
[index[0] for index in sorted_count.index[:5]]

In [ ]:
plot2(joint.loc[[index[0] for index in sorted_count.index[:5]],:])

In [ ]:
joint[joint.index[0]]

In [ ]:
fig, ax = plt.subplots(figsize = (15,15))
man.plot(ax = ax, color = 'green')
joint.plot(**{'edgecolor': 'red'}, ax = ax)

In [ ]:
A = get_matrix('100.csv')
inspect(A)

In [ ]:
fig, ax = plt.subplots(figsize = (10,5))
#ax.hist(A.sum(axis = 0), bins = 15,range = (0,15))
ax.hist(A.sum(axis = 1), bins = 15,range = (0,15))

In [ ]:
count[(832.0, 978.0)]

In [ ]:
t.do.max()

In [ ]:
count.pu.max()

In [ ]:
tax = pd.read_csv(r'yellow_tripdata_2016-01.csv',
                    usecols=['dropoff_longitude', 'dropoff_latitude', 'pickup_longitude', 'pickup_latitude'],
                    chunksize = 10000, dtype =np.float32, nrows = 30000)
trips = get_trips(tax.get_chunk())
man = get_zones()
joint = get_joint_grid(man, 100, 0)